on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: connect and pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd kitsheet.cz/web
          git checkout main
          git pull
          php artisan down
          composer install
          php artisan migrate
          npm install
          npm run build
          php artisan cache:clear
          php artisan sitemap:create
          php artisan up
